/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.zadanie11_2;
import javax.swing.JOptionPane;

/**
 *
 * @author preme
 */
public class Kalkulator_ukladow_rownan extends javax.swing.JFrame {

    /**
     * Creates new form Kalkulator_ukladow_rownan
     */
    public Kalkulator_ukladow_rownan() {
        initComponents();
         Widzialnosc(0);
         Informacja.setVisible(false);
         Oblicztxt.setVisible(false);
         Cleartxt.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ntxt = new javax.swing.JTextField();
        Podaj = new javax.swing.JLabel();
        OKK = new javax.swing.JButton();
        Ws11 = new javax.swing.JTextField();
        X1 = new javax.swing.JLabel();
        Ws12 = new javax.swing.JTextField();
        X2 = new javax.swing.JLabel();
        Ws14 = new javax.swing.JTextField();
        Ws13 = new javax.swing.JTextField();
        Informacja = new javax.swing.JLabel();
        X3 = new javax.swing.JLabel();
        X4 = new javax.swing.JLabel();
        Ws15 = new javax.swing.JTextField();
        Eq1 = new javax.swing.JTextField();
        Zatwierdzacz1 = new javax.swing.JButton();
        Oblicztxt = new javax.swing.JButton();
        Cleartxt = new javax.swing.JButton();
        X5 = new javax.swing.JLabel();
        Ws16 = new javax.swing.JTextField();
        X6 = new javax.swing.JLabel();
        Ws17 = new javax.swing.JTextField();
        X7 = new javax.swing.JLabel();
        Rownanie1 = new javax.swing.JLabel();
        Rownanie2 = new javax.swing.JLabel();
        Rownanie3 = new javax.swing.JLabel();
        Rownanie4 = new javax.swing.JLabel();
        Rownanie5 = new javax.swing.JLabel();
        Rownanie6 = new javax.swing.JLabel();
        Rownanie7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        Ntxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NtxtActionPerformed(evt);
            }
        });

        Podaj.setBackground(new java.awt.Color(255, 255, 255));
        Podaj.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        Podaj.setText("Podaj liczbe rownan(7<n<2)");

        OKK.setText("Zatwierdź");
        OKK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKKActionPerformed(evt);
            }
        });

        Ws11.setToolTipText("");

        X1.setText("x1+");

        X2.setText("x2+");

        Informacja.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N

        X3.setText("x3+");

        X4.setText("x4+");

        Zatwierdzacz1.setText("Zatwierdź");
        Zatwierdzacz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Zatwierdzacz1ActionPerformed(evt);
            }
        });

        Oblicztxt.setBackground(new java.awt.Color(255, 255, 204));
        Oblicztxt.setText("Oblicz");
        Oblicztxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OblicztxtActionPerformed(evt);
            }
        });

        Cleartxt.setText("Wyczyść");
        Cleartxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CleartxtActionPerformed(evt);
            }
        });

        X5.setText("x5+");

        X6.setText("x6+");

        X7.setText("x7=");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Rownanie6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Rownanie1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Rownanie2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Rownanie3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Rownanie5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Rownanie4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Rownanie7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(176, 176, 176))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Oblicztxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Podaj)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Ntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(OKK)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(Informacja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Cleartxt, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Ws11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(X1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Ws12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(X2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Ws13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(X3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Ws14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(X4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Ws15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(X5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Ws16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(X6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Ws17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(X7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Eq1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Zatwierdzacz1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(12, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Podaj)
                    .addComponent(Ntxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OKK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Informacja, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ws11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ws12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(X1)
                            .addComponent(X2)
                            .addComponent(Ws13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(X3)
                            .addComponent(Ws14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(X4)
                            .addComponent(Ws15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(X5)
                            .addComponent(Ws16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(X6)
                            .addComponent(Ws17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(X7)
                            .addComponent(Eq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Zatwierdzacz1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Oblicztxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Rownanie1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Rownanie2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Rownanie3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Rownanie4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Rownanie5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Rownanie6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Rownanie7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Cleartxt)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int n;
    int j=0;
   
    double [][]tab;
    double []W;
    public double[][] Ustalanie_macierzy(int wsp){
       double [][]tabpom;
       
       tabpom=new double[n][n];
            for(int i=0;i<n;i++ ){
                for(int j=0;j<n;j++){
                    if(wsp==j){
                        tabpom[i][j]=tab[i][n];
                    }
                    else{
                        tabpom[i][j]=tab[i][j];
                    }
                }
                
            }
            return tabpom;
        }
    public double[][] macierz_pom(double pom[][],int rozmiar,int k,int w){
        double m[][];
        int a=0;
        int b=0;
        m= new double[rozmiar-1][rozmiar-1]; 
        for(int i=0;i<rozmiar;i++){
            b=0;
            for(int j=0;j<rozmiar;j++){
                if(i!=w && j!=k){
                    m[a][b]=pom[i][j];
                    b++;
                }
            }
            if(i!=w) a++;
            
        }
        return m;
    }
    public double Obliczanie_macierzy(double pom[][],int rozmiar){
         
        double detA;
        if(rozmiar==3){
            
            double sum1;
            double sum2;
            sum1=(pom[0][0]*pom[1][1]*pom[2][2])+(pom[0][1]*pom[1][2]*pom[2][0])+(pom[0][2]*pom[1][0]*pom[2][1]);
            sum2=(pom[2][0]*pom[1][1]*pom[0][2])+(pom[2][1]*pom[1][2]*pom[0][0])+(pom[0][1]*pom[1][0]*pom[2][2]);
            detA=sum1-sum2;
            
        }
        else {
            
         detA=0;
         for(int i=0;i<rozmiar;i++){
             detA+=Math.pow(-1,(i+1+1))*pom[0][i]*Obliczanie_macierzy(macierz_pom(pom,rozmiar,i,0),rozmiar-1);
         }   
        }
       
       return detA;
       
    }
    public void WD13(int n){
        boolean wd;
        if(n>=3){
            wd=true;
        }
        else{
            wd=false;
        }
        Zatwierdzacz1.setVisible(wd);
        X1.setVisible(wd);
        Ws11.setEnabled(wd);
        Ws11.setVisible(wd);
        Ws12.setEnabled(wd);
        Ws12.setVisible(wd);
        X2.setVisible(wd);
        X3.setVisible(wd);
        Ws13.setVisible(wd);
        Ws13.setEnabled(wd);
        Eq1.setVisible(wd);
        Eq1.setEnabled(wd);
        if(n==3){
            X3.setText("x3=");
            
        }
        else{
            X3.setText("x3+");
        }
    }
    public void WD4(int n){
        boolean wd;
        if(n>=4){
            wd=true;
        }
        else{
            wd=false;
        }
         Ws14.setVisible(wd);
         Ws14.setEnabled(wd);
         X4.setVisible(wd);
         if(n==4){
             X4.setText("x4=");
         }
         else{
            X4.setText("x4+"); 
         }
    }
    public void WD5(int n){
        boolean wd;
        if(n>=5){
            wd=true;
        }
        else{
            wd=false;
        }
         Ws15.setVisible(wd);
         Ws15.setEnabled(wd);
         X5.setVisible(wd);
         if(n==5){
             X5.setText("x5=");
         }
         else{
            X5.setText("x5+"); 
         }
    }
    public void WD6(int n){
        boolean wd;
        if(n>=6){
            wd=true;
        }
        else{
            wd=false;
        }
         Ws16.setVisible(wd);
         Ws16.setEnabled(wd);
         X6.setVisible(wd);
         if(n==6){
             X6.setText("x6=");
         }
         else{
            X6.setText("x6+"); 
         }
    }
    public void WD7(int n){
        boolean wd;
        if(n==7){
            wd=true;
        }
        else{
            wd=false;
        }
         Ws17.setVisible(wd);
         Ws17.setEnabled(wd);
         X7.setVisible(wd);
         if(n==7){
             X7.setText("x7=");
         }
         
    }
    
    public void Widzialnosc(int n){
        WD13(n);
        WD4(n);
        WD5(n);
        WD6(n);
        WD7(n);
        
        
        
    }
   
    private void OKKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKKActionPerformed
        // TODO add your handling code here:
        try{
            String l=Ntxt.getText();
            n=Integer.parseInt(l);
            if(n<3 || n>7) {
                throw new ArithmeticException();
            }
            Ntxt.setEnabled(false);
            Podaj.setText("Liczba niewiadomych :");
            
            Informacja.setVisible(true);
            Informacja.setText("Podaj wspolczynniki");
            Widzialnosc(n);
            Oblicztxt.setVisible(true);
            Oblicztxt.setEnabled(false);
            Cleartxt.setVisible(true);
            OKK.setVisible(false);
            tab=new double[n][n+1];
        }catch(NumberFormatException e){
            Ntxt.setText("");
            Informacja.setVisible(true);
            Informacja.setText("Podaj n jeszcze raz");
        }catch(ArithmeticException e){
            Ntxt.setText("");
              Informacja.setVisible(true);
            Informacja.setText("Podaj n jeszcze raz");
        }
        
        
    }//GEN-LAST:event_OKKActionPerformed
    public void Wsp4(boolean udalosie){
          try{
        tab[j][3]=Double.parseDouble(Ws14.getText());
        }catch(NumberFormatException e){
            Informacja.setText("Wprowadz współczynniki jeszcze raz !");
            udalosie=false;
        }
        Ws14.setText("");
    }
    public void Wsp5(boolean udalosie){
          try{
        tab[j][4]=Double.parseDouble(Ws15.getText());
        }catch(NumberFormatException e){
            Informacja.setText("Wprowadz współczynniki jeszcze raz !");
            udalosie=false;
        }
        Ws15.setText("");
    }
    public void Wsp6(boolean udalosie){
          try{
        tab[j][5]=Double.parseDouble(Ws16.getText());
        }catch(NumberFormatException e){
            Informacja.setText("Wprowadz współczynniki jeszcze raz !");
            udalosie=false;
        }
        Ws16.setText("");
    }
    public void Wsp7(boolean udalosie){
          try{
        tab[j][6]=Double.parseDouble(Ws17.getText());
        }catch(NumberFormatException e){
            Informacja.setText("Wprowadz współczynniki jeszcze raz !");
            udalosie=false;
        }
        Ws17.setText("");
    }
    public String Row(){
        String r="";
        for(int i=0;i<n;i++){
            if(i!=0 && tab[j][i]>=0) r+="+";
            r+=Double.toString(tab[j][i])+"*x"+Integer.toString(i+1);
            
        }
        r+="="+Double.toString(tab[j][n]);
        return r;
    }
    private void Zatwierdzacz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Zatwierdzacz1ActionPerformed
        // TODO add your handling code here:
        boolean udalosie=true;
        try{
        tab[j][0]=Double.parseDouble(Ws11.getText());
        }catch(NumberFormatException e){
            Informacja.setText("Wprowadz współczynniki jeszcze raz !");
            udalosie=false;
        }
        Ws11.setText("");
        try{
        tab[j][1]=Double.parseDouble(Ws12.getText());
        }catch(NumberFormatException e){
            Informacja.setText("Wprowadz współczynniki jeszcze raz !");
            udalosie=false;
        }
        Ws12.setText("");
        try{
        tab[j][2]=Double.parseDouble(Ws13.getText());
        }catch(NumberFormatException e){
            Informacja.setText("Wprowadz współczynniki jeszcze raz !");
            udalosie=false;
        }
        Ws13.setText("");
        if(n==4){
          Wsp4(udalosie);
        }
        else if(n==5){
            Wsp4(udalosie);
            Wsp5(udalosie);
            
        }
        else if(n==6){
            Wsp4(udalosie);
            Wsp5(udalosie);
            Wsp6(udalosie);
        }
        else if(n==7){
            Wsp4(udalosie);
            Wsp5(udalosie);
            Wsp6(udalosie);
            Wsp7(udalosie);
        }
        
          try{
        tab[j][n]=Double.parseDouble(Eq1.getText());
        }catch(NumberFormatException e){
            Informacja.setText("Wprowadz współczynniki jeszcze raz !");
            udalosie=false;
        }
        Eq1.setText("");
        if(udalosie==true){
            if(j==0) Rownanie1.setText(Row());
            else if(j==1) Rownanie2.setText(Row());
            else if(j==2) Rownanie3.setText(Row());
            else if(j==3) Rownanie4.setText(Row());
            else if(j==4) Rownanie5.setText(Row());
            else if(j==5) Rownanie6.setText(Row());
            else if(j==6) Rownanie7.setText(Row());
            j++;
        }
        if(j==n-1){
            Oblicztxt.setVisible(true);
            Oblicztxt.setEnabled(false);
        }
        else if(j==n){
            Ws11.setEnabled(false);
            Ws12.setEnabled(false);
            Ws13.setEnabled(false);
            Ws14.setEnabled(false);
            Ws15.setEnabled(false);
            Ws16.setEnabled(false);
            Ws17.setEnabled(false);
            Eq1.setEnabled(false);
            Oblicztxt.setEnabled(true);
            
            
            
            
        }
    }//GEN-LAST:event_Zatwierdzacz1ActionPerformed

    private void CleartxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CleartxtActionPerformed
        // TODO add your handling code here:
        Widzialnosc(0);
        OKK.setVisible(true);
        OKK.setEnabled(true);
        Ntxt.setEnabled(true);
        Ntxt.setText("");
        Informacja.setText("");
        Podaj.setText("Podaj liczbe rownan(7<n<2):");
        j=0;
        n=0;
        Oblicztxt.setEnabled(false);
        Oblicztxt.setVisible(false);
        Rownanie1.setText("");
        Rownanie2.setText("");
        Rownanie3.setText("");
        Rownanie4.setText("");
        Rownanie5.setText("");
        Rownanie6.setText("");
        Rownanie7.setText("");
        Cleartxt.setVisible(false);
    }//GEN-LAST:event_CleartxtActionPerformed

    private void OblicztxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OblicztxtActionPerformed
        // TODO add your handling code here:
        
        W=new double[n+1];
        double pom[][];
        String wiadomosc="";
        
        for(int i=0;i<=n;i++){
            pom=new double[n][n];
            pom=Ustalanie_macierzy(i);
            W[i]=Obliczanie_macierzy(pom,n); 
            
        }
        if(W[n]==0){
            wiadomosc="Nie mozna rozwiazac ukladu !";
        }
        else{
            for(int i=0;i<n;i++){
                W[i]=W[i]/W[n];
                wiadomosc+="x"+Integer.toString(i+1)+"="+Double.toString(W[i])+"\n";
            }
        }
        JOptionPane.showMessageDialog(rootPane,wiadomosc);
    }//GEN-LAST:event_OblicztxtActionPerformed

    private void NtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NtxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            
            java.util.logging.Logger.getLogger(Kalkulator_ukladow_rownan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator_ukladow_rownan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator_ukladow_rownan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator_ukladow_rownan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator_ukladow_rownan().setVisible(true);
                
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cleartxt;
    private javax.swing.JTextField Eq1;
    private javax.swing.JLabel Informacja;
    private javax.swing.JTextField Ntxt;
    private javax.swing.JButton OKK;
    private javax.swing.JButton Oblicztxt;
    private javax.swing.JLabel Podaj;
    private javax.swing.JLabel Rownanie1;
    private javax.swing.JLabel Rownanie2;
    private javax.swing.JLabel Rownanie3;
    private javax.swing.JLabel Rownanie4;
    private javax.swing.JLabel Rownanie5;
    private javax.swing.JLabel Rownanie6;
    private javax.swing.JLabel Rownanie7;
    private javax.swing.JTextField Ws11;
    private javax.swing.JTextField Ws12;
    private javax.swing.JTextField Ws13;
    private javax.swing.JTextField Ws14;
    private javax.swing.JTextField Ws15;
    private javax.swing.JTextField Ws16;
    private javax.swing.JTextField Ws17;
    private javax.swing.JLabel X1;
    private javax.swing.JLabel X2;
    private javax.swing.JLabel X3;
    private javax.swing.JLabel X4;
    private javax.swing.JLabel X5;
    private javax.swing.JLabel X6;
    private javax.swing.JLabel X7;
    private javax.swing.JButton Zatwierdzacz1;
    // End of variables declaration//GEN-END:variables
}
